### ISSUE TITLE
ES6 Arrow Notation

### ISSUE THREAD

**Issue by Reewr** [Reewr/vim-monokai-phoenix#5]
ES6 Arrow Notation is not highlighted with the right color. The arrow itself should be aqua-colored. It is now red.

The colors of the arguments within a Arrow function is not highlighted either. Must be fixed through syntax.

**Comment by Reewr** [comment]
Made a feature request for this in [vim-javascript-syntax](https://github.com/jelera/vim-javascript-syntax/issues/63)

**Comment by graingert** [comment]
@Reewr maybe use YAJS?

**Comment by Reewr** [comment]
@graingert As a temporary solution, I have now moved over to vim-javascript, which has a lot of the same features as vim-javascript-syntax. The main benefit of vim-javascript is its folding, where I have yet to see it fail, unlike vim-javascript-syntax.

I'll look into YAJS though, it looks pretty decent.

**Comment by Reewr** [comment]
This works correctly with the current version of [vim-javascript](https://github.com/pangloss/vim-javascript).
